package com.sadeghjfr22.covid19.utils

import com.sadeghjfr22.covid19.view.fragment.CountryFragment.Companion.allCountries

object Translate {


    fun translateCountryNames(){

        for (item in allCountries){

            when(item.name){

                "Afghanistan" -> item.name = "افغانستان"
                "Albania" -> item.name = "آلبانی"
                "Algeria" -> item.name = "الجزایر"
                "Andorra" -> item.name = "آندورا"
                "Angola" -> item.name = "آنگولا"
                "Antigua and Barbuda" -> item.name = "آنتیگوآ و باربودا"
                "Argentina" -> item.name = "آرژانتین"
                "Armenia" -> item.name = "ارمنستان"
                "Australia" -> item.name = "استرالیا"
                "Austria" -> item.name = "اتریش"
                "Azerbaijan" -> item.name = "آذربایجان"
                "Bahamas" -> item.name = "باهاما"
                "Bahrain" -> item.name = "بحرین"
                "Bangladesh" -> item.name = "بنگلادش"
                "Barbados" -> item.name = "باربادوس"
                "Belarus" -> item.name = "بلاروس"
                "Belgium" -> item.name = "بلژیک"
                "Belize" -> item.name = "بلیز"
                "Benin" -> item.name = "بنین"
                "Bhutan" -> item.name = "بوتان"
                "Bolivia" -> item.name = "بلیوی"
                "Bosnia and Herzegovina" -> item.name = "بوسنی و هرزگوین"
                "Botswana" -> item.name = "بوتسوانا"
                "Brazil" -> item.name = "برزیل"
                "Brunei Darussalam" -> item.name = "برونئی"
                "Bulgaria" -> item.name = "بلغارستان"
                "Burkina Faso" -> item.name = "بورکینافاسو"
                "Burundi" -> item.name = "بوروندی"
                "Cambodia" -> item.name = "کامبوج"
                "Cameroon" -> item.name = "کامرون"
                "Canada" -> item.name = "کانادا"
                "Cape Verde" -> item.name = "کیپ ورد"
                "Central African Republic" -> item.name = "آفریقای مرکزی"
                "Chad" -> item.name = "چاد"
                "Chile" -> item.name = "شیلی"
                "China" -> item.name = "چین"
                "Colombia" -> item.name = "کلمبیا"
                "Comoros" -> item.name = "کومور"
                "Congo (Brazzaville)" -> item.name = "کنگوی برازاویل"
                "Congo (Kinshasa)" -> item.name = "جمهوری کنگو"
                "Costa Rica" -> item.name = "کاستاریکا"
                "Croatia" -> item.name = "کرواسی"
                "Cuba" -> item.name = "کوبا"
                "Cyprus" -> item.name = "قبرس"
                "Czech Republic" -> item.name = "جمهوری چک"
                "Côte d'Ivoire" -> item.name = "ساحل عاج"
                "Denmark" -> item.name = "دانمارک"
                "Djibouti" -> item.name = "جیبوتی"
                "Dominica" -> item.name = "دومینیکا"
                "Dominican Republic" -> item.name = "جمهوری دومینیکن"
                "Ecuador" -> item.name = "اکوادور"
                "Egypt" -> item.name = "مصر"
                "El Salvador" -> item.name = "السالوادور"
                "Equatorial Guinea" -> item.name = "گینه استوایی"
                "Eritrea" -> item.name = "اریتره"
                "Estonia" -> item.name = "استونی"
                "Ethiopia" -> item.name = "اتیوپی"
                "Fiji" -> item.name = "فیجی"
                "Finland" -> item.name = "فنلاند"
                "France" -> item.name = "فرانسه"
                "Gabon" -> item.name = "گابن"
                "Gambia" -> item.name = "گامبیا"
                "Georgia" -> item.name = "گرجستان"
                "Germany" -> item.name = "آلمان"
                "Ghana" -> item.name = "غنا"
                "Greece" -> item.name = "یونان"
                "Grenada" -> item.name = "گرنادا"
                "Guatemala" -> item.name = "گواتمالا"
                "Guinea" -> item.name = "گینه"
                "Guinea-Bissau" -> item.name = "گینه بیسائو"
                "Guyana" -> item.name = "گویان"
                "Haiti" -> item.name = "هائیتی"
                "Holy See (Vatican City State)" -> item.name = "واتیکان"
                "Honduras" -> item.name = "هندوراس"
                "Hungary" -> item.name = "مجارستان"
                "Iceland" -> item.name = "ایسلند"
                "India" -> item.name = "هندوستان"
                "Indonesia" -> item.name = "اندونزی"
                "Iran, Islamic Republic of" -> item.name = "ایران"
                "Iraq" -> item.name = "عراق"
                "Ireland" -> item.name = "ایرلند"
                "Israel" -> item.name = "اسرائیل"
                "Italy" -> item.name = "ایتالیا"
                "Jamaica" -> item.name = "جامائیکا"
                "Japan" -> item.name = "ژاپن"
                "Jordan" -> item.name = "اردن"
                "Kazakhstan" -> item.name = "قزاقستان"
                "Kenya" -> item.name = "کنیا"
                "Korea (South)" -> item.name = "کره جنوبی"
                "Kuwait" -> item.name = "کویت"
                "Kyrgyzstan" -> item.name = "قرقیزستان"
                "Lao PDR" -> item.name = "لائوس"
                "Latvia" -> item.name = "لتونی"
                "Lebanon" -> item.name = "لبنان"
                "Lesotho" -> item.name = "لسوتو"
                "Liberia" -> item.name = "لیبریا"
                "Libya" -> item.name = "لیبی"
                "Liechtenstein" -> item.name = "لیختن اشتاین"
                "Lithuania" -> item.name = "لیتوانی"
                "Luxembourg" -> item.name = "لوکزامبورگ"
                "Macedonia, Republic of" -> item.name = "جمهوری مقدونیه"
                "Madagascar" -> item.name = "ماداگاسکار"
                "Malawi" -> item.name = "مالاوی"
                "Malaysia" -> item.name = "مالزی"
                "Maldives" -> item.name = "مالدیو"
                "Mali" -> item.name = "مالی"
                "Malta" -> item.name = "مالت"
                "Marshall Islands" -> item.name = "جزایر مارشال"
                "Mauritania" -> item.name = "موریتانی"
                "Mauritius" -> item.name = "موریس"
                "Mexico" -> item.name = "مکزیک"
                "Micronesia, Federated States of" -> item.name = "ایالات فدرال میکرونزی"
                "Moldova" -> item.name = "مولداوی"
                "Monaco" -> item.name = "موناکو"
                "Mongolia" -> item.name = "مغولستان"
                "Montenegro" -> item.name = "مونته نگرو"
                "Morocco" -> item.name = "مراکش"
                "Mozambique" -> item.name = "موزامبیک"
                "Myanmar" -> item.name = "میانمار"
                "Namibia" -> item.name = "نامیبیا"
                "Nepal" -> item.name = "نپال"
                "Netherlands" -> item.name = "هلند"
                "New Zealand" -> item.name = "نیوزلند"
                "Nicaragua" -> item.name = "نیکاراگوئه"
                "Niger" -> item.name = "نیجر"
                "Nigeria" -> item.name = "نیجریه"
                "Norway" -> item.name = "نروژ"
                "Oman" -> item.name = "عمان"
                "Pakistan" -> item.name = "پاکستان"
                "Palestinian Territory" -> item.name = "فلسطین"
                "Panama" -> item.name = "پاناما"
                "Papua New Guinea" -> item.name = "پاپوآ  گینه نو"
                "Paraguay" -> item.name = "پاراگوئه"
                "Peru" -> item.name = "پرو"
                "Philippines" -> item.name = "فیلیپین"
                "Poland" -> item.name = "لهستان"
                "Portugal" -> item.name = "پرتغال"
                "Qatar" -> item.name = "قطر"
                "Republic of Kosovo" -> item.name = "جمهوری کوزوو"
                "Romania" -> item.name = "رومانی"
                "Russian Federation" -> item.name = "روسیه"
                "Rwanda" -> item.name = "رواندا"
                "Saint Kitts and Nevis" -> item.name = "سنت کیتس و نویس"
                "Saint Lucia" -> item.name = "سنت لوسیا"
                "Saint Vincent and Grenadines" -> item.name = "سنت وینسنت و گرنادین"
                "Samoa" -> item.name = "ساموآ"
                "San Marino" -> item.name = "سن مارینو"
                "Sao Tome and Principe" -> item.name = "سائوتومه و پرینسیپ"
                "Saudi Arabia" -> item.name = "عربستان سعودی"
                "Senegal" -> item.name = "سنگال"
                "Serbia" -> item.name = "صربستان"
                "Seychelles" -> item.name = "سیشل"
                "Sierra Leone" -> item.name = "سیر الئون"
                "Singapore" -> item.name = "سنگاپور"
                "Slovakia" -> item.name = "اسلواکی"
                "Slovenia" -> item.name = "اسلوونی"
                "Solomon Islands" -> item.name = "جزایر سلیمان"
                "Somalia" -> item.name = "سومالی"
                "South Africa" -> item.name = "آفریقای جنوبی"
                "South Sudan" -> item.name = "سودان جنوبی"
                "Spain" -> item.name = "اسپانیا"
                "Sri Lanka" -> item.name = "سریلانکا"
                "Sudan" -> item.name = "سودان"
                "Suriname" -> item.name = "سورینام"
                "Swaziland" -> item.name = "اسواتینی"
                "Sweden" -> item.name = "سوئد"
                "Switzerland" -> item.name = "سوئیس"
                "Syrian Arab Republic (Syria)" -> item.name = "سوریه"
                "Taiwan, Republic of China" -> item.name = "تایوان"
                "Tajikistan" -> item.name = "تاجیکستان"
                "Tanzania, United Republic of" -> item.name = "تانزانیا"
                "Thailand" -> item.name = "تایلند"
                "Timor-Leste" -> item.name = "تیمور شرقی"
                "Togo" -> item.name = "توگو"
                "Trinidad and Tobago" -> item.name = "ترینیداد و توباگو"
                "Tunisia" -> item.name = "تونس"
                "Turkey" -> item.name = "ترکیه"
                "Uganda" -> item.name = "اوگاندا"
                "Ukraine" -> item.name = "اوکراین"
                "United Arab Emirates" -> item.name = "امارات متحده عربی"
                "United Kingdom" -> item.name = "انگلستان"
                "United States of America" -> item.name = "ایالات متحده آمریکا"
                "Uruguay" -> item.name = "اروگوئه"
                "Uzbekistan" -> item.name = "ازبکستان"
                "Vanuatu" -> item.name = "وانواتو"
                "Venezuela (Bolivarian Republic)" -> item.name = "ونزوئلا"
                "Viet Nam" -> item.name = "ویتنام"
                "Yemen" -> item.name = "یمن"
                "Zambia" -> item.name = "زامبیا"
                "Zimbabwe" -> item.name = "زیمبابوه"


            }

        }


    }

    fun translateRegion(){

        for (item in allCountries){

            when(item.region){

                "Asia" -> item.region = "آسیا"
                "Europe" -> item.region = "اروپا"
                "Africa" -> item.region = "آفریقا"
                "Americas" -> item.region = "آمریکا"
                "Oceania" -> item.region = "اقیانوسیه"
            }
        }
    }

    fun translateCapital(){

        for (item in allCountries){

            when(item.capital){

                "Kabul" -> item.capital = "کابل"
                "Tirana" -> item.capital = "تیرانا"
                "Algiers" -> item.capital = "الجزیره"
                "Andorra la Vella" -> item.capital = "آندورا لاولا"
                "Luanda" -> item.capital = "لوآندا"
                "Saint John's" -> item.capital = "سینت جانز"
                "Buenos Aires" -> item.capital = "بوئنوس آیرس"
                "Yerevan" -> item.capital = "ایروان"
                "Canberra" -> item.capital = "کانبرا"
                "Vienna" -> item.capital = "وین"
                "Baku" -> item.capital = "باکو"
                "Nassau" -> item.capital = "ناسائو"
                "Manama" -> item.capital = "منامه"
                "Dhaka" -> item.capital = "داکا"
                "Bridgetown" -> item.capital = "بریج تاون"
                "Minsk" -> item.capital = "مینسک"
                "Brussels" -> item.capital = "بروکسل"
                "Belmopan" -> item.capital = "بلموپان"
                "Porto-Novo" -> item.capital = "پورتو نووو"
                "Thimphu" -> item.capital = "تیمفو"
                "Sucre" -> item.capital = "سوکره"
                "Sarajevo" -> item.capital = "سارایوو"
                "Gaborone" -> item.capital = "گابورون"
                "Brasília" -> item.capital = "برازیلیا"
                "Bandar Seri Begawan" -> item.capital = "بندر سری بگاوان"
                "Sofia" -> item.capital = "صوفیه"
                "Ouagadougou" -> item.capital = "آواگادوگو"
                "Bujumbura" -> item.capital = "بوجومبورا"
                "Phnom Penh" -> item.capital = "پنوم پن"
                "Yaoundé" -> item.capital = "یائونده"
                "Ottawa" -> item.capital = "اتاوا"
                "Praia" -> item.capital = "پرایا"
                "Bangui" -> item.capital = "بانگی"
                "N'Djamena" -> item.capital = "انجامنا"
                "Santiago" -> item.capital = "سانتیاگو"
                "Beijing" -> item.capital = "پکن"
                "Bogotá" -> item.capital = "بوگوتا"
                "Moroni" -> item.capital = "مورونی"
                "Brazzaville" -> item.capital = "برازاویل"
                "Kinshasa" -> item.capital = "کینشاسا"
                "San José" -> item.capital = "سان خوزه"
                "Zagreb" -> item.capital = "زاگرب"
                "Havana" -> item.capital = "هاوانا"
                "Nicosia" -> item.capital = "نیکوزیا"
                "Prague" -> item.capital = "پراگ"
                "Yamoussoukro" -> item.capital = "یاموسوکرو"
                "Copenhagen" -> item.capital = "کپنهاگ"
                "Djibouti" -> item.capital = "جیبوتی"
                "Roseau" -> item.capital = "روسو"
                "Santo Domingo" -> item.capital = "سانتو دومینگو"
                "Quito" -> item.capital = "کیتو"
                "Cairo" -> item.capital = "قاهره"
                "San Salvador" -> item.capital = "سان سالوادور"
                "Malabo" -> item.capital = "مالابو"
                "Asmara" -> item.capital = "اسمره"
                "Tallinn" -> item.capital = "تالین"
                "Addis Ababa" -> item.capital = "آدیس آبابا"
                "Suva" -> item.capital = "سووا"
                "Helsinki" -> item.capital = "هلسینکی"
                "Paris" -> item.capital = "پاریس"
                "Libreville" -> item.capital = "لیبرویل"
                "Banjul" -> item.capital = "بانجول"
                "Tbilisi" -> item.capital = "تفلیس"
                "Berlin" -> item.capital = "برلین"
                "Accra" -> item.capital = "آکرا"
                "Athens" -> item.capital = "آتن"
                "St. George's" -> item.capital = "سینت جورجس"
                "Guatemala City" -> item.capital = "گواتمالا سیتی"
                "Conakry" -> item.capital = "کوناکری"
                "Bissau" -> item.capital = "بیسائو"
                "Georgetown" -> item.capital = "جرج تاون"
                "Port-au-Prince" -> item.capital = "پورتو پرنس"
                "Tegucigalpa" -> item.capital = "تگوسیگالپا"
                "Budapest" -> item.capital = "بوداپست"
                "Reykjavík" -> item.capital = "ریکیاویک"
                "New Delhi" -> item.capital = "دهلی نو"
                "Jakarta" -> item.capital = "جاکارتا"
                "Tehran" -> item.capital = "تهران"
                "Baghdad" -> item.capital = "بغداد"
                "Dublin" -> item.capital = "دوبلین"
                "Jerusalem" -> item.capital = "اورشلیم"
                "Rome" -> item.capital = "رم"
                "Kingston" -> item.capital = "کینگستون"
                "Tokyo" -> item.capital = "توکیو"
                "Amman" -> item.capital = "عمان ( امان )"
                "Astana" -> item.capital = "آستانه ( نور سلطان )"
                "Nairobi" -> item.capital = "نایروبی"
                "Seoul" -> item.capital = "س_ئول"
                "Kuwait City" -> item.capital = "کویت"
                "Bishkek" -> item.capital = "بیشکک"
                "Vientiane" -> item.capital = "وینتیان"
                "Riga" -> item.capital = "ریگا"
                "Beirut" -> item.capital = "بیروت"
                "Maseru" -> item.capital = "ماسرو"
                "Monrovia" -> item.capital = "مونروویا"
                "Tripoli" -> item.capital = "طرابلس"
                "Vaduz" -> item.capital = "فادوتس"
                "Vilnius" -> item.capital = "ویلنیوس"
                "Luxembourg" -> item.capital = "لوکزامبورگ"
                "Skopje" -> item.capital = "اسکوپیه"
                "Antananarivo" -> item.capital = "آنتاناناریوو"
                "Lilongwe" -> item.capital = "لیلونگوه"
                "Kuala Lumpur" -> item.capital = "کوالالامپور"
                "Malé" -> item.capital = "ماله"
                "Bamako" -> item.capital = "باماکو"
                "Valletta" -> item.capital = "والتا"
                "Majuro" -> item.capital = "ماجورو"
                "Nouakchott" -> item.capital = "نواکشوت"
                "Port Louis" -> item.capital = "پورت لوئیس"
                "Mexico City" -> item.capital = "مکزیکو سیتی"
                "Palikir" -> item.capital = "پالیکیر"
                "Chișinău" -> item.capital = "کیشیناو"
                "Monaco" -> item.capital = "موناکو ویل"
                "Ulan Bator" -> item.capital = "اولان باتور"
                "Podgorica" -> item.capital = "پودگوریتسا"
                "Rabat" -> item.capital = "رباط"
                "Maputo" -> item.capital = "ماپوتو"
                "Naypyidaw" -> item.capital = "نایپیداو"
                "Windhoek" -> item.capital = "ویندهوک"
                "Kathmandu" -> item.capital = "کاتماندو"
                "Amsterdam" -> item.capital = "آمستردام"
                "Wellington" -> item.capital = "ولینگتون"
                "Managua" -> item.capital = "ماناگوآ"
                "Niamey" -> item.capital = "نیامی"
                "Abuja" -> item.capital = "آبوجا"
                "Oslo" -> item.capital = "اسلو"
                "Muscat" -> item.capital = "مسقط"
                "Islamabad" -> item.capital = "اسلام آباد"
                "Ramallah" -> item.capital = "رام الله"
                "Panama City" -> item.capital = "پاناما سیتی"
                "Port Moresby" -> item.capital = "پورت مورسبی"
                "Asunción" -> item.capital = "آسونسیون"
                "Lima" -> item.capital = "لیما"
                "Manila" -> item.capital = "مانیل"
                "Warsaw" -> item.capital = "ورشو"
                "Lisbon" -> item.capital = "لیسبون"
                "Doha" -> item.capital = "دوحه"
                "Pristina" -> item.capital = "پریشتینا"
                "Bucharest" -> item.capital = "بخارست"
                "Moscow" -> item.capital = "مسکو"
                "Kigali" -> item.capital = "کیگالی"
                "Basseterre" -> item.capital = "باسه تر"
                "Castries" -> item.capital = "کاستریس"
                "Kingstown" -> item.capital = "کینگستون"
                "Apia" -> item.capital = "آپیا"
                "City of San Marino" -> item.capital = "سن مارینو"
                "São Tomé" -> item.capital = "سائوتومه"
                "Riyadh" -> item.capital = "ریاض"
                "Dakar" -> item.capital = "داکار"
                "Belgrade" -> item.capital = "بلگراد"
                "Victoria" -> item.capital = "ویکتوریا"
                "Freetown" -> item.capital = "فری تاون"
                "Singapore" -> item.capital = "سنگاپور"
                "Bratislava" -> item.capital = "براتیسلاوا"
                "Ljubljana" -> item.capital = "لیوبلیانا"
                "Honiara" -> item.capital = "هونیارا"
                "Mogadishu" -> item.capital = "موگادیشو"
                "Pretoria" -> item.capital = "پرتوریا"
                "Juba" -> item.capital = "جوبا"
                "Madrid" -> item.capital = "مادرید"
                "Colombo" -> item.capital = "کلمبو"
                "Khartoum" -> item.capital = "خارطوم"
                "Paramaribo" -> item.capital = "پاراماریبو"
                "Lobamba" -> item.capital = "لوبامبا"
                "Stockholm" -> item.capital = "استکهلم"
                "Bern" -> item.capital = "برن"
                "Damascus" -> item.capital = "دمشق"
                "Taipei" -> item.capital = "تایپه"
                "Dushanbe" -> item.capital = "دوشنبه"
                "Dodoma" -> item.capital = "دودوما"
                "Bangkok" -> item.capital = "بانکوک"
                "Dili" -> item.capital = "دیلی"
                "Lomé" -> item.capital = "لومه"
                "Port of Spain" -> item.capital = "پرت آو اسپاین ( بندر اسپانیا )"
                "Tunis" -> item.capital = "تونس"
                "Ankara" -> item.capital = "آنکارا"
                "Kampala" -> item.capital = "کامپالا"
                "Kiev" -> item.capital = "کی\u200Cیف"
                "Abu Dhabi" -> item.capital = "ابوظبی"
                "London" -> item.capital = "لندن"
                "Washington, D.C." -> item.capital = "واشینگتن، دی.سی"
                "Montevideo" -> item.capital = "مونته ویدئو"
                "Tashkent" -> item.capital = "تاشکند"
                "Port Vila" -> item.capital = "پورت ویلا"
                "Caracas" -> item.capital = "کاراکاس"
                "Hanoi" -> item.capital = "هانوی"
                "Sana'a" -> item.capital = "صنعا"
                "Lusaka" -> item.capital = "لوساکا"
                "Harare" -> item.capital = "هراره"
            }
        }

        setVaticanCapital()
    }

    fun setVaticanCapital(){

        for (item in allCountries){

            if (item.name.equals("واتیکان"))
                item.capital = "واتیکان سیتی"
        }
    }

}